index:
   path: /
   controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
   defaults:
        template: 'home/index.html.twig'

register_get:
   path: /register
   controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
   methods: GET
   defaults:
        template: 'register/register.html.twig'

register_post:
   path: /register
   controller: App\Controller\UserController::register
   methods: POST

home:
   path: /home
   controller: App\Controller\DefaultController::home

page:
   path: /page
   controller: App\Controller\PageController::index

login_get:
   path: /login
   controller: App\Controller\UserController::getLogin
   methods: GET

login_post:
   path: /login
   controller: App\Controller\UserController::postLogin
   methods: POST

logout:
   path: /logout
   controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
   defaults:
      path: /
      permanent: true

add_event_get:
   path: /home/event/add
   controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
   methods: GET
   defaults:
        template: 'home/register-event.html.twig'

add_event_post:
   path: /api/event/add
   controller: App\Controller\EventController::register
   methods: POST
