name: Continous Integration

on: [pull_request]

jobs:
  pre-check:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate composer.json and composer.lock
        run: composer validate

  lint:
    runs-on: ubuntu-latest
    needs: pre-check
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Twig
        run: php bin/console lint:twig templates/;
      - name: YAML
        run: php bin/console lint:yaml config/;
      - name: PHP Code Sniffer
        run: ./vendor/bin/phpcs;
      - name: PHP Stan
        run: ./vendor/bin/phpstan analyse --no-progress;

  test:
    runs-on: ubuntu-latest
    needs: pre-check
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: PHP UNIT
        run: ./vendor/bin/simple-phpunit;
